// Code generated by MockGen. DO NOT EDIT.
// Source: feature-flag-manager/internal/http/handler (interfaces: FeatureUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mocks.go -package=mocks feature-flag-manager/internal/http/handler FeatureUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "feature-flag-manager/internal/domain"
	service "feature-flag-manager/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeatureUseCase is a mock of FeatureUseCase interface.
type MockFeatureUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureUseCaseMockRecorder
	isgomock struct{}
}

// MockFeatureUseCaseMockRecorder is the mock recorder for MockFeatureUseCase.
type MockFeatureUseCaseMockRecorder struct {
	mock *MockFeatureUseCase
}

// NewMockFeatureUseCase creates a new mock instance.
func NewMockFeatureUseCase(ctrl *gomock.Controller) *MockFeatureUseCase {
	mock := &MockFeatureUseCase{ctrl: ctrl}
	mock.recorder = &MockFeatureUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureUseCase) EXPECT() *MockFeatureUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeatureUseCase) Create(arg0 context.Context, arg1 service.WriteFeature) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFeatureUseCaseMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeatureUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockFeatureUseCase) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeatureUseCaseMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeatureUseCase)(nil).Delete), arg0, arg1)
}

// Evaluate mocks base method.
func (m *MockFeatureUseCase) Evaluate(arg0 context.Context, arg1, arg2 string) (domain.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockFeatureUseCaseMockRecorder) Evaluate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockFeatureUseCase)(nil).Evaluate), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockFeatureUseCase) Get(arg0 context.Context, arg1 string) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFeatureUseCaseMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFeatureUseCase)(nil).Get), arg0, arg1)
}

// Health mocks base method.
func (m *MockFeatureUseCase) Health(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockFeatureUseCaseMockRecorder) Health(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockFeatureUseCase)(nil).Health), arg0)
}

// List mocks base method.
func (m *MockFeatureUseCase) List(arg0 context.Context) ([]domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeatureUseCaseMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeatureUseCase)(nil).List), arg0)
}

// RefreshCache mocks base method.
func (m *MockFeatureUseCase) RefreshCache(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshCache", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshCache indicates an expected call of RefreshCache.
func (mr *MockFeatureUseCaseMockRecorder) RefreshCache(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshCache", reflect.TypeOf((*MockFeatureUseCase)(nil).RefreshCache), arg0)
}

// Update mocks base method.
func (m *MockFeatureUseCase) Update(arg0 context.Context, arg1 string, arg2 service.WriteFeature) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeatureUseCaseMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeatureUseCase)(nil).Update), arg0, arg1, arg2)
}
