// Code generated by MockGen. DO NOT EDIT.
// Source: feature-flag-manager/internal/repository (interfaces: FeatureRepository,FeatureCache)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mocks.go -package=mocks feature-flag-manager/internal/repository FeatureRepository,FeatureCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "feature-flag-manager/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeatureRepository is a mock of FeatureRepository interface.
type MockFeatureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureRepositoryMockRecorder
	isgomock struct{}
}

// MockFeatureRepositoryMockRecorder is the mock recorder for MockFeatureRepository.
type MockFeatureRepositoryMockRecorder struct {
	mock *MockFeatureRepository
}

// NewMockFeatureRepository creates a new mock instance.
func NewMockFeatureRepository(ctrl *gomock.Controller) *MockFeatureRepository {
	mock := &MockFeatureRepository{ctrl: ctrl}
	mock.recorder = &MockFeatureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureRepository) EXPECT() *MockFeatureRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeatureRepository) Create(arg0 context.Context, arg1 domain.Feature) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFeatureRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeatureRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockFeatureRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeatureRepositoryMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeatureRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockFeatureRepository) Get(arg0 context.Context, arg1 string) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFeatureRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFeatureRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockFeatureRepository) List(arg0 context.Context) ([]domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeatureRepositoryMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeatureRepository)(nil).List), arg0)
}

// Ping mocks base method.
func (m *MockFeatureRepository) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockFeatureRepositoryMockRecorder) Ping(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockFeatureRepository)(nil).Ping), arg0)
}

// Update mocks base method.
func (m *MockFeatureRepository) Update(arg0 context.Context, arg1 domain.Feature) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeatureRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeatureRepository)(nil).Update), arg0, arg1)
}

// MockFeatureCache is a mock of FeatureCache interface.
type MockFeatureCache struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureCacheMockRecorder
	isgomock struct{}
}

// MockFeatureCacheMockRecorder is the mock recorder for MockFeatureCache.
type MockFeatureCacheMockRecorder struct {
	mock *MockFeatureCache
}

// NewMockFeatureCache creates a new mock instance.
func NewMockFeatureCache(ctrl *gomock.Controller) *MockFeatureCache {
	mock := &MockFeatureCache{ctrl: ctrl}
	mock.recorder = &MockFeatureCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureCache) EXPECT() *MockFeatureCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFeatureCache) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeatureCacheMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeatureCache)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockFeatureCache) Get(arg0 context.Context, arg1 string) (domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFeatureCacheMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFeatureCache)(nil).Get), arg0, arg1)
}

// Ping mocks base method.
func (m *MockFeatureCache) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockFeatureCacheMockRecorder) Ping(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockFeatureCache)(nil).Ping), arg0)
}

// Replace mocks base method.
func (m *MockFeatureCache) Replace(arg0 context.Context, arg1 []domain.Feature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockFeatureCacheMockRecorder) Replace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockFeatureCache)(nil).Replace), arg0, arg1)
}

// Set mocks base method.
func (m *MockFeatureCache) Set(arg0 context.Context, arg1 domain.Feature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockFeatureCacheMockRecorder) Set(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockFeatureCache)(nil).Set), arg0, arg1)
}
